[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
command = """
  bash ./netlify-setup.sh &&
  git clone https://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@github.com/romannaltae/tina.git content &&
  find content -mindepth 1 ! -path "content/content*" -delete && mv content/content/* content && rmdir content/content/ &&
  hugo --minify --gc
  """
publish = "public/"

[build.environment]
HUGO_VERSION = "0.103.0"
HUGO_BASEURL = "/"


# активировать при производстве
#[[plugins]]
#  package = "netlify-plugin-submit-sitemap"
#
#  [plugins.inputs]
#  # The base url of your site (optional, default = main URL set in Netlify)
#  baseUrl = "https://belshops.ru"
#
#  # Path to the sitemap URL (optional, default = /sitemap.xml)
#  sitemapPath = "/sitemap.xml"
#
#  # Time in seconds to not submit the sitemap after successful submission
#  ignorePeriod = 0
#
#  # Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
#  providers = [
#    "google",
#    "yandex"
#  ]

