[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  command = """
    npm run build
  """
  publish = "out/"

[[plugins]]
	package = "netlify-plugin-cloudinary"

[plugins.inputs]
	cloudName = "dr8es8hbw"

	[plugins.inputs]
		cloudName = "dr8es8hbw"
		deliveryType = "upload"
		uploadPreset = "[Your Cloudinary Upload Preset]"